#!/bin/bash
hwinfo --block --short 2> /dev/null > /home/linaro/Rlags_project/scripts/drives/device_list
grep Apricorn /home/linaro/Rlags_project/scripts/drives/device_list | awk '{print $1}'> /home/linaro/Rlags_project/scripts/drives/drive_list
grep -f /home/linaro/Rlags_project/scripts/drives/drive_list /home/linaro/Rlags_project/scripts/drives/device_list | grep Partition | awk '{print $1}' > /home/linaro/Rlags_project/scripts/drives/partition_list
exit
