#!/bin/bash
DRIVES=$(grep -c '' partition_list)
COUNTER=0
while [ $COUNTER -lt $DRIVES ];
do
NUMBER=NR==$COUNTER+1
PARTITION=$(awk $NUMBER partition_list)
sudo umount $PARTITION
let COUNTER=COUNTER+1
done
exit
